export const ERROR_MESSAGES = {
  INTERNAL_SERVER_ERROR: 'Internal server error',
  SESSION_NOT_FOUND: 'Session not found',
  COOKIES_NOT_FOUND: 'Cookies not found',
  ACCESS_TOKEN_NOT_FOUND: 'Access token not found',
  INVALID_TOKEN: 'Invalid token',
  INVALID_CREDS: 'Invalid credentials',
  INVALID_DATA: 'Invalid data',
  EMPTY_DATA: 'Empty data',
  ACCESS_DENIED: 'Access Denied',
  USER_EXISTS: 'User already exists',
  USER_IS_NOT_EXISTS: 'User is not exists',
  DB_ERROR: 'Error by query to database',
  AGENT_NOT_FOUND: 'Agent not found',
  ONE_FIELD_REQUIRED: 'At least one property must be provided',
  REDIS_ERROR: 'Redis error',
  PASSWORDS_NOT_MATCH: 'Passwords do not match',
  PERMISSIONS_NOT_PROVIDED: 'Permissions not provided',
  REQUIRED_PERMISSIONS: 'Required permissions must me provided',
};
