export enum PermissionsKeys {
  // Agents
  READ_AGENTS = 'READ_AGENTS',
  CREATE_AGENTS = 'CREATE_AGENTS',
  UPDATE_AGENTS = 'UPDATE_AGENTS',
  DELETE_AGENTS = 'DELETE_AGENTS',

  // Leads / Customers
  READ_LEADS = 'READ_LEADS',
  CREATE_LEADS = 'CREATE_LEADS',
  UPDATE_LEADS = 'UPDATE_LEADS',
  DELETE_LEADS = 'DELETE_LEADS',
  ASSIGN_LEADS = 'ASSIGN_LEADS',

  // Roles
  READ_ROLES = 'READ_ROLES',
  CREATE_ROLES = 'CREATE_ROLES',
  UPDATE_ROLES = 'UPDATE_ROLES',
  DELETE_ROLES = 'DELETE_ROLES',

  // Desks
  READ_DESKS = 'READ_DESKS',
  CREATE_DESKS = 'CREATE_DESKS',
  UPDATE_DESKS = 'UPDATE_DESKS',
  DELETE_DESKS = 'DELETE_DESKS',

  // Teams
  READ_TEAMS = 'READ_TEAMS',
  CREATE_TEAMS = 'CREATE_TEAMS',
  UPDATE_TEAMS = 'UPDATE_TEAMS',
  DELETE_TEAMS = 'DELETE_TEAMS',
  ASSIGN_AGENTS_TO_TEAMS = 'ASSIGN_AGENTS_TO_TEAMS',
}
